import type { Lead } from "@/types/lead";

export const dummyLeads: Lead[] = [
  {
    id: '1',
    entity: "ABC Financial Services",
    contact: "Rahul Mehta",
    mobile: "9876543210",
    email: "rahul@abc.com",
    location: "Delhi",
    products: ["CRM", "Website", "Mobile App"],
    status: "New",
    owner: "Amit Sharma",
    assigned: "Amit Sharma",
    followup: "2026-09-07",
    key: "",
    notes: "Sent CRM brochure; call scheduled today.",
  },
  {
    id: '2',
    entity: "Growth Investments",
    contact: "Priya Sinha",
    mobile: "9812345678",
    email: "priya@growth.com",
    location: "Mumbai",
    products: ["Mutual Fund", "IPO"],
    status: "In Process",
    owner: "Neha Verma",
    assigned: "Neha Verma",
    followup: "2026-09-07",
    key: "",
    notes: "Waiting on KYC docs before proposal.",
  },
  {
    id: '3',
    entity: "Sunrise Traders",
    contact: "Karan Malhotra",
    mobile: "9987654321",
    email: "karan@sunrise.com",
    location: "Bengaluru",
    products: ["Ecommerce", "SEO"],
    status: "Meeting",
    owner: "Rohit Kumar",
    assigned: "Rohit Kumar",
    followup: "2026-09-12",
    key: "Meeting: 2026-09-05 (Online)",
    meetingDate: "2026-09-05",
    meetingType: "Online",
  },
  {
    id: '4',
    entity: "Wealth Discovery",
    contact: "Anil Gupta",
    mobile: "9876501234",
    email: "anil@wealth.com",
    location: "Noida",
    products: ["Mobile App", "LMS"],
    status: "Completed",
    owner: "Sneha Iyer",
    assigned: "Sneha Iyer",
    followup: "",
    key: "Won: 2026-09-03",
    wonDate: "2026-09-03",
  },
  {
    id: '5',
    entity: "Metro Enterprises",
    contact: "Suresh Nair",
    mobile: "9865409876",
    email: "suresh@metro.com",
    location: "Chennai",
    products: ["Ticketing System", "CRM"],
    status: "Lost",
    owner: "Amit Sharma",
    assigned: "Amit Sharma",
    followup: "",
    key: "Lost: 2026-09-01",
    lostDate: "2026-09-01",
  },
  {
    id: '6',
    entity: "NextGen Advisors",
    contact: "Kavita Rao",
    mobile: "9822334455",
    email: "kavita@nextgen.com",
    location: "Hyderabad",
    products: ["Client Onboarding", "Digital Market"],
    status: "In Process",
    owner: "Neha Verma",
    assigned: "Neha Verma",
    followup: "2026-09-15",
    key: "",
  },
  {
    id: '7',
    entity: "Elite Portfolio",
    contact: "Vikram Singh",
    mobile: "9877896541",
    email: "vikram@elite.com",
    location: "Pune",
    products: ["Mutual Fund", "Website"],
    status: "Meeting",
    owner: "Rohit Kumar",
    assigned: "Rohit Kumar",
    followup: "2026-09-09",
    key: "Meeting: 2026-09-07 (Offline)",
    meetingDate: "2026-09-07",
    meetingType: "Offline",
  },
];
