import type { LeadActivity } from "@/types/activity";

export const dummyActivities: LeadActivity[] = [
  {
    id: "a1",
    leadId: '1',
    type: "created",
    message: "Lead created from inbound enquiry",
    createdAt: "2026-09-04T09:20:00",
    actor: "Amit Sharma",
  },
  {
    id: "a2",
    leadId: '1',
    type: "note",
    message: "Shared CRM brochure and pricing sheet over email.",
    createdAt: "2026-09-05T11:10:00",
    actor: "Amit Sharma",
  },
  {
    id: "a3",
    leadId: '1',
    type: "followup",
    message: "Follow-up scheduled",
    createdAt: "2026-09-05T11:15:00",
    actor: "Amit Sharma",
    meta: { to: "2026-09-07" },
  },
  {
    id: "a4",
    leadId: '2',
    type: "created",
    message: "Lead imported from partner list",
    createdAt: "2026-09-02T14:00:00",
    actor: "Neha Verma",
  },
  {
    id: "a5",
    leadId: '2',
    type: "status_change",
    message: "Status updated",
    createdAt: "2026-09-03T10:30:00",
    actor: "Neha Verma",
    meta: { from: "New", to: "In Process" },
  },
  {
    id: "a6",
    leadId: '2',
    type: "note",
    message: "Discussed mutual fund onboarding flow; waiting on KYC docs.",
    createdAt: "2026-09-06T16:45:00",
    actor: "Neha Verma",
  },
  {
    id: "a7",
    leadId: '2',
    type: "followup",
    message: "Follow-up moved to today",
    createdAt: "2026-09-06T16:50:00",
    actor: "Neha Verma",
    meta: { from: "2026-09-08", to: "2026-09-07" },
  },
  {
    id: "a8",
    leadId: '3',
    type: "meeting",
    message: "Online discovery meeting completed",
    createdAt: "2026-09-05T15:00:00",
    actor: "Rohit Kumar",
    meta: { to: "2026-09-05" },
  },
  {
    id: "a9",
    leadId: '3',
    type: "note",
    message: "Client liked ecommerce + SEO package; send revised quote.",
    createdAt: "2026-09-05T16:20:00",
    actor: "Rohit Kumar",
  },
  {
    id: "a10",
    leadId: '4',
    type: "status_change",
    message: "Deal marked won",
    createdAt: "2026-09-03T12:00:00",
    actor: "Sneha Iyer",
    meta: { from: "Meeting", to: "Completed" },
  },
  {
    id: "a11",
    leadId: '5',
    type: "status_change",
    message: "Lead marked lost",
    createdAt: "2026-09-01T18:00:00",
    actor: "Amit Sharma",
    meta: { from: "In Process", to: "Lost" },
  },
  {
    id: "a12",
    leadId: '7',
    type: "meeting",
    message: "Offline product walkthrough booked for today",
    createdAt: "2026-09-06T09:00:00",
    actor: "Rohit Kumar",
    meta: { to: "2026-09-07" },
  },
  {
    id: "a13",
    leadId: '7',
    type: "assignment",
    message: "Assigned to owner",
    createdAt: "2026-09-01T11:00:00",
    actor: "System",
    meta: { to: "Rohit Kumar" },
  },
];
